name: HaggleXCaleb Node CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Clean Install Dependencies & Build Application
        run: |
          yarn install --frozen-lockfile
          yarn build

  test:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Test Application
        run: docker-compose -f docker-compose.test.yml up
